name=leoLib
version=1.0.0
author=leogad Hakizimana<hakizimanaleogad@gmail.com>
maintainer=leogad Hakizimana<hakizimanaleogad@gmail.com>
sentence=Minimalist library for ultrasound module to Arduino
paragraph="This Library is Compatible With HC-SR04 module of Ultrasonic"
Category=Sensor
url=https://github.com/leogad123/leoLib(Ultrasonic)
architectures=*
includes=leoLib.h
